plugins {
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.kapt)
}

android {
    compileSdk project.findProperty("compileSdk") as Integer

    defaultConfig {
        applicationId project.findProperty("appId") as String
        namespace project.findProperty("nameSpace") as String
        minSdk project.findProperty("minSdk") as Integer
        targetSdk project.findProperty("targetSdk") as Integer
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file(project.findProperty("keystoreFile") as String)
            storePassword project.findProperty("keystorePassword") as String
            keyAlias project.findProperty("keyAlias") as String
            keyPassword project.findProperty("keyPassword") as String

        }
    }

    buildTypes {
        debug {
            debuggable true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }

        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = libs.versions.jvm.get()
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar", "*.aar"])

    implementation libs.kotlin.stdlib
    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.fragment.ktx
    implementation libs.preference.ktx
    implementation libs.kotlinx.coroutines.core

    testImplementation libs.junit
    testImplementation libs.junit.jupiter
    testImplementation libs.testng
    testImplementation libs.ext.junit
    testImplementation libs.espresso.core
    testImplementation libs.kotlinx.coroutines.test

    implementation libs.arch

    // alternately-if using Java8, use following instead of compiler
    implementation libs.common.java8

    def exoplayer = libs.shoplive.exoplayer.get()
    def exoplaver_version = libs.versions.exoPlayer.get()
    def shopliveExoPlayerSuffix = libs.versions.shopliveExoPlayerSuffix.get()
    
    // For submodules
    implementation libs.shoplive.common // must required
    implementation("$exoplayer:${exoplaver_version}${shopliveExoPlayerSuffix}")  // must required

    // When using media3. Exoplayer will be deprecated soon.
    // https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide
    // implementation "cloud.shoplive:shoplive-media3:$shoplive_media3_version"
    implementation libs.shoplive.network // must required
    implementation libs.shoplive.sdk.core // for live player
    implementation libs.shoplive.short.form // for short-form player
    implementation libs.shoplive.filter // for short-form editor
    implementation libs.shoplive.video.editor // for short-form editor

    testImplementation libs.mockk.test
    testImplementation libs.core.testing

    // For library - combined packaging
    // implementation libs.shoplive.sdk.all // live + short-form
}
